[package]
name = "lite-clojure-eval"
version = "0.1.0"
edition = "2018"


[features]
default = ["eval_core"]
eval_core = []

[dependencies]
lite-clojure-parser = {path = "../lite-clojure-parser"}
gc = { version = "0.4.1", features = ["derive"] }